### ISSUE TITLE
Need a local webserver to open index.html?

### ISSUE THREAD

**Issue by OmarShehata** [StoDevX/PaperCut-Scraper#1]
Since it tries to load an external file, just double clicking on index.html leads to this console error:

`XMLHttpRequest cannot load file:///E:/experiments/misc/PaperCut-Scraper/data/data.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

Perhaps mentioning that in the readme instructions? (Unless there's a way to make it work without a local server?)

**Comment by drewvolz** [comment]
It's possible to disable cross-origin and local file restrictions, but it is not recommended. @hawkrives update to the README helps clarify one way by starting a local web server with Python.
